server.port=8765
spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# RUTE
spring.cloud.gateway.server.webflux.routes[0].id=vehicle-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://vehicle-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/vehicles/**

spring.cloud.gateway.server.webflux.routes[1].id=reservation-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://reservation-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/reservations/**

spring.cloud.gateway.server.webflux.routes[2].id=category-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://vehicle-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/categories/**

spring.cloud.gateway.server.webflux.routes[3].id=location-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://vehicle-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/locations/**

spring.cloud.gateway.server.webflux.routes[4].id=user-service-auth
spring.cloud.gateway.server.webflux.routes[4].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webflux.routes[5].id=user-service-me
spring.cloud.gateway.server.webflux.routes[5].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/me

spring.cloud.gateway.server.webflux.routes[6].id=payment-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://payment-service
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/payments/**

# Iskljucen discovery locator, koristimo rucno definisane rute
spring.cloud.gateway.server.webflux.discovery.locator.enabled=false

# Actuator - informacije o serveru
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.enabled=true

# Logovanje
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.com.rzk.api_gateway.security=DEBUG
