spring.application.name=eureka-server

server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Bitno za Docker (da drugi servisi mogu da se registruju)
eureka.instance.hostname=eureka-server
